CREATE OR REPLACE TABLE CHIPS_DATA_MODEL.Customers_DIM AS
SELECT LYLTY_CARD_NBR AS Customer_ID, 
       LIFESTAGE AS Customer_Segment , 
       PREMIUM_CUSTOMER AS Customer_Category
FROM RAW_DATA.PURCHASE_BEHAVIOUR