CREATE OR REPLACE TABLE CHIPS_DATA_MODEL.SAUCES_DIM AS
SELECT DISTINCT 
    PROD_NBR AS Product_ID,
    REGEXP_REPLACE(PROD_NAME, '[0-9]+g', '') AS Product_Name,
    ARRAY_TO_STRING(ARRAY_SLICE(SPLIT(PROD_NAME, ' '), 0, 3), ' ') AS Brand_Name,
    REGEXP_SUBSTR(PROD_NAME, '[0-9]+') AS Package_Size
FROM RAW_DATA.TRANSACTION_DATA   
WHERE LOWER(PROD_NAME) LIKE '%sauce%'
   OR LOWER(PROD_NAME) LIKE '%dip%'
   OR LOWER(PROD_NAME) LIKE '%salsa%'
   OR LOWER(PROD_NAME) LIKE '%mild%';
